// AUTO-GENERATED by Ardo - Do not edit manually

import { type RouteConfig, route, index } from "@react-router/dev/routes"

export default [
  index("routes/home.tsx"),
  route("imprint", "routes/imprint.tsx"),
  route("privacy", "routes/privacy.tsx"),
] satisfies RouteConfig
